## Environment setup

In [1]:
!python3 -m venv venv
!source venv/bin/activate

**Warning**: switch kernel to venv in upper right corner

In [1]:
!pip3 install -r requirements.txt

Collecting pandas (from -r requirements.txt (line 1))
  Downloading pandas-3.0.2-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting numpy (from -r requirements.txt (line 2))
  Using cached numpy-2.4.4-cp314-cp314-macosx_14_0_arm64.whl.metadata (6.6 kB)
Collecting kagglehub (from -r requirements.txt (line 3))
  Downloading kagglehub-1.0.0-py3-none-any.whl.metadata (40 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.14/site-packages (from pandas->-r requirements.txt (line 1)) (2.9.0.post0)
Collecting kagglesdk<1.0,>=0.1.14 (from kagglehub->-r requirements.txt (line 3))
  Downloading kagglesdk-0.1.18-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in ./venv/lib/python3.14/site-packages (from kagglehub->-r requirements.txt (line 3)) (26.0)
Collecting pyyaml (from kagglehub->-r requirements.txt (line 3))
  Using cached pyyaml-6.0.3-cp314-cp314-macosx_11_0_arm64.whl.metadata (2.4 kB)
Collecting requests (from kagglehub->-r requirements.txt (line 3))
  Downloading requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Collecting tqdm (from kagglehub->-r requirements.txt (line 3))
  Using cached tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting protobuf (from kagglesdk<1.0,>=0.1.14->kagglehub->-r requirements.txt (line 3))
  Downloading protobuf-7.34.1-cp310-abi3-macosx_10_9_universal2.whl.metadata (595 bytes)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 1)) (1.17.0)
Collecting charset_normalizer<4,>=2 (from requests->kagglehub->-r requirements.txt (line 3))
  Downloading charset_normalizer-3.4.7-cp314-cp314-macosx_10_15_universal2.whl.metadata (40 kB)
Collecting idna<4,>=2.5 (from requests->kagglehub->-r requirements.txt (line 3))
  Downloading idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.26 (from requests->kagglehub->-r requirements.txt (line 3))
  Using cached urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests->kagglehub->-r requirements.txt (line 3))
  Using cached certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Downloading pandas-3.0.2-cp314-cp314-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 2.3 MB/s  0:00:04a 0:00:01m eta 0:00:01
Using cached numpy-2.4.4-cp314-cp314-macosx_14_0_arm64.whl (5.2 MB)
Downloading kagglehub-1.0.0-py3-none-any.whl (70 kB)
Downloading kagglesdk-0.1.18-py3-none-any.whl (201 kB)
Downloading protobuf-7.34.1-cp310-abi3-macosx_10_9_universal2.whl (429 kB)
Using cached pyyaml-6.0.3-cp314-cp314-macosx_11_0_arm64.whl (173 kB)
Downloading requests-2.33.1-py3-none-any.whl (64 kB)
Downloading charset_normalizer-3.4.7-cp314-cp314-macosx_10_15_universal2.whl (309 kB)
Downloading idna-3.11-py3-none-any.whl (71 kB)
Using cached urllib3-2.6.3-py3-none-any.whl (131 kB)
Using cached certifi-2026.2.25-py3-none-any.whl (153 kB)
Using cached tqdm-4.67.3-py3-none-any.whl (78 kB)
Installing collected packages: urllib3, tqdm, pyyaml, protobuf, numpy, idna, charset_normalizer, certifi, requests, pandas, kagglesdk, kagglehub
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12/12 [kagglehub][0m 10/12 [kagglesdk]a]
Successfully installed certifi-2026.2.25 charset_normalizer-3.4.7 idna-3.11 kagglehub-1.0.0 kagglesdk-0.1.18 numpy-2.4.4 pandas-3.0.2 protobuf-7.34.1 pyyaml-6.0.3 requests-2.33.1 tqdm-4.67.3 urllib3-2.6.3

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

## Imports

In [2]:
import os
import shutil

import numpy as np
import pandas as pd

import kagglehub
from kagglehub import KaggleDatasetAdapter

/Users/aleklyskawa/Desktop/FootballPlayersAnalysis/venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Downloading data

In [3]:
download_path = kagglehub.dataset_download("kaanyorgun/european-top-leagues-player-stats-25-26")

my_path = os.path.join(os.getcwd(), 'data')

shutil.move(download_path, my_path)

Downloading to /Users/aleklyskawa/.cache/kagglehub/datasets/kaanyorgun/european-top-leagues-player-stats-25-26/13.archive...

100%|██████████| 177k/177k [00:00<00:00, 532kB/s]

Extracting files...

'/Users/aleklyskawa/Desktop/FootballPlayersAnalysis/data/13'

## Loading data

In [5]:
profiles_df = pd.read_csv('data/9/all_player_profiles.csv')
stats_df = pd.read_csv('data/9/all_player_stats.csv')

## Data analysis

In [7]:
profiles_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   player_id     4277 non-null   int64
 1   name          4277 non-null   str
 2   league        4277 non-null   str
 3   position      4277 non-null   str
 4   market_value  4068 non-null   float64
dtypes: float64(1), int64(1), str(3)
memory usage: 167.2 KB

In [8]:
stats_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3675 entries, 0 to 3674
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         3675 non-null   int64
 1   league            3675 non-null   str
 2   appearances       3675 non-null   int64
 3   matches_started   3675 non-null   int64
 4   minutes_played    3675 non-null   int64
 5   goals             3675 non-null   int64
 6   assists           3675 non-null   int64
 7   expected_goals    3134 non-null   float64
 8   expected_assists  3655 non-null   float64
 9   rating            3675 non-null   float64
 10  total_shots       3675 non-null   int64
 11  shots_on_target   3675 non-null   int64
 12  yellow_cards      3675 non-null   int64
 13  red_cards         3675 non-null   int64
 14  tackles           3675 non-null   int64
 15  interceptions     3675 non-null   int64
 16  saves             3675 non-null   int64
dtypes: float64(3), int64(13), str(1)
memory usage: 488.2 KB

In [9]:
profiles_df.isna().sum()

player_id         0
name              0
league            0
position          0
market_value    209
dtype: int64

In [10]:
stats_df.isna().sum()

player_id             0
league                0
appearances           0
matches_started       0
minutes_played        0
goals                 0
assists               0
expected_goals      541
expected_assists     20
rating                0
total_shots           0
shots_on_target       0
yellow_cards          0
red_cards             0
tackles               0
interceptions         0
saves                 0
dtype: int64

## Cleaning

In [11]:
values = {'market_value' : 0.0}
profiles_df = profiles_df.fillna(value=values)
profiles_df.head()

   player_id                name          league position  market_value
0     804508     Viktor Gyökeres  Premier League        F    61000000.0
1     934235         Bukayo Saka  Premier League        F   136000000.0
2     794839       Gabriel Jesus  Premier League        F    21000000.0
3     922573  Gabriel Martinelli  Premier League        F    42000000.0
4     836705         Kai Havertz  Premier League        F    48000000.0

In [12]:
values = {'expected_goals': 0.0, 'expected_assists': 0.0}
stats_df = stats_df.fillna(value=values)
stats_df.head()

,player_id,league,appearances,matches_started,minutes_played,goals,assists,expected_goals,expected_assists,rating,total_shots,shots_on_target,yellow_cards,red_cards,tackles,interceptions,saves
0,804508,Premier League,29,23,1907,11,0,9.3498,1.767505,6.572414,43,17,4,0,6,1,0
1,934235,Premier League,27,22,2001,6,3,6.9941,5.761951,7.214815,63,26,1,0,36,14,0
2,794839,Premier League,11,2,306,2,0,1.7605,0.203329,6.527273,14,9,2,0,4,2,0
3,922573,Premier League,25,9,852,1,3,3.3793,0.991020,6.616000,25,10,2,0,10,0,0
4,836705,Premier League,6,3,264,0,1,0.3077,0.097873,6.650000,5,1,0,0,3,0,0